CREATE DATABASE develop_database CHARACTER SET utf8mb4;
show databases;
use mysql;

GRANT ALL PRIVILEGES ON *.* TO root@127.0.0.1;
GRANT ALL PRIVILEGES ON *.* TO root@10.0.2.2;
GRANT ALL PRIVILEGES ON *.* TO root@192.168.33.10;

FLUSH PRIVILEGES;
